### ISSUE TITLE
师傅，class web server没有请求呢，不知道为什么？

### ISSUE THREAD

**Issue by hktalent** [jas502n/SpringBoot_Actuator_RCE#1]
师傅，class web server没有请求呢，不知道为什么？
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/18223385/82402031-03529a00-9a8e-11ea-8a87-ae3ad2eb8b94.png">

**Comment by hktalent** [comment]
11:27:56,115 |-ERROR in ch.qos.logback.classic.joran.action.InsertFromJNDIAction - [rmi://192.168.79.181:1099/xxxClass] has null or empty value

 java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

Mac OS 10.15.4

**Comment by jas502n** [comment]
jdk 版本问题?

51pwn_com <notifications@github.com> 于2020年5月20日周三 上午11:49写道：

**Comment by hktalent** [comment]
@jas502n class是jdk1.6输出，运行的监听是jdk1.8
